### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by eregon**
This lets this gem build from the repo on recent Rubies and on TruffleRuby.

### CODE REVIEW

**Comment by iliabylich** [comment]
Oof, CIs are not triggered anymore, maybe because the repo hasn't been updated for a long time. I'll run tests locally in a few hours and merge without CI. Thanks for the PR!

**Comment by iliabylich** [comment]
How is its performance on TruffleRuby by the way? Is it as slow Ripper?

**Comment by eregon** [comment]
I didn't measure it but since it doesn't compile (https://github.com/whitequark/parser/issues/871#issuecomment-1325000345) it can't be good.

**Comment by iliabylich** [comment]
Works for me 😄 . Thanks, merging

**Comment by iliabylich** [comment]
@eregon Ragel supports more backends for C, here's the size of the `advance` method:

T0 mode = 4042 LOC
T1 mode = 8399 LOC
F0 mode = 4000 LOC
F1 mode = 8357 LOC
G0 mode = 19825 LOC
G1 and G2 are even worse.

Could you try changing mode to T0 or F0 in Rakefile to see it makes it better?

**Pull request merged**
